/*
   Copyright 2011-2012 StormMQ Limited

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

 /* This file is used to examine the assembly code generated by the fast mutex operations */

#include "Thread/FastMutex.h"

static int shared_data;

int fast_mutex_usage()
{
    int result;

    amqp_fast_mutex_t mutex;

    amqp_fast_mutex_initialize(&mutex);

    amqp_fast_mutex_lock(&mutex);
    result = ++shared_data;
    amqp_fast_mutex_unlock(&mutex);

    amqp_fast_mutex_destroy(&mutex);

    return result;
}

int fast_mutex_usage_with_arg(amqp_fast_mutex_t *mutex)
{
    int result;

    amqp_fast_mutex_lock(mutex);
    result = ++shared_data;
    amqp_fast_mutex_unlock(mutex);

    return result;
}


int fast_mutex_usage_with_many_args(int *shared_data, amqp_fast_mutex_t *mutex)
{
    int result;

    amqp_fast_mutex_lock(mutex);
    result = ++(*shared_data);
    amqp_fast_mutex_unlock(mutex);

    return result;
}

