/*
   Copyright 2011 StormMQ Limited

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

#include "platform_limits.h"
#include "libamqp_common.h"

#include <assert.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include "Memory/Memory.h"
#include "Context/Context.h"
#include "Context/ErrorHandling.h"


#define SIZE_T_BYTES (sizeof(size_t))
static const size_t mask = (size_t) 0x996e796d586067caULL;      // generated by random.org

typedef struct amqp__memory_block_t
{
    size_t count;
    size_t mask;
    union {
        long double alignment_insurance;
        size_t fragments[2];
    } data;
} amqp__memory_block_t;

static inline size_t byte_count_rounded_to_size_t_array_size(size_t n)
{
    return (n - 1) / SIZE_T_BYTES + 1;
}

static inline size_t calculate_bytes_to_allocate(size_t count)
{
    return sizeof(amqp__memory_block_t) + (count - 1) * SIZE_T_BYTES;
}

static inline void save_guard_mask(amqp__memory_block_t *block, size_t count)
{
    block->count = count;
    block->mask = mask;
    block->data.fragments[count] = mask ^ count;
}

void *amqp_malloc(amqp_context_t *context, size_t n)
{
    size_t count = byte_count_rounded_to_size_t_array_size(n);
    amqp__memory_block_t *block = (amqp__memory_block_t *) malloc(calculate_bytes_to_allocate(count));

    if (context != 0)
    {
        context->memory.allocation_stats.outstanding_allocations++;
        context->memory.allocation_stats.total_allocation_calls++;
    }

    save_guard_mask(block, count);

    memset(&block->data.fragments[0], '\0', count * SIZE_T_BYTES);

    return &block->data.fragments[0];
}

static inline amqp__memory_block_t *calculate_block_start(void *p)
{
    static amqp__memory_block_t layout;

    return (amqp__memory_block_t *) ((unsigned char *) p - ((unsigned char *) &layout.data.fragments[0] - (unsigned char *) &layout.count));
}

static void assert_leading_guard_correct(amqp__memory_block_t *block)
{
    if (block->mask != mask)
    {
        printf("Start of block corrupt! Block: %p, mask: %lu\n",
            (void *) block, (unsigned long) block->mask);
        abort();
    }
}

static void assert_trailing_guard_correct(amqp__memory_block_t *block)
{
    size_t count = block->count;
    if (block->data.fragments[count] != (mask ^ count))
    {
        printf("End of block corrupt! Block: %p, count: %lu, block[count]: %lx\n",
            (void *) block, (unsigned long) count, (unsigned long) block->data.fragments[count]);
        abort();
    }
}

void *amqp_realloc(amqp_context_t *context, void *p, size_t n)
{
    amqp__memory_block_t *old_block = calculate_block_start(p);
    size_t old_count;
    size_t count;
    amqp__memory_block_t *block;

    assert_leading_guard_correct(old_block);
    assert_trailing_guard_correct(old_block);

    old_count = old_block->count;
    count = byte_count_rounded_to_size_t_array_size(n);
    if (count <= old_count)
    {
        return p;
    }

    block = (amqp__memory_block_t *) realloc(old_block, calculate_bytes_to_allocate(count));

    memset(&block->data.fragments[old_count], '\0', (count - old_count) * SIZE_T_BYTES);

    if (context != 0)
    {
        context->memory.allocation_stats.total_allocation_calls++;
    }
    save_guard_mask(block, count);

    return &block->data.fragments[0];
}

void amqp_free(amqp_context_t *context, void *p)
{
    amqp__memory_block_t *block;

    if (p)
    {
        block = calculate_block_start(p);

        assert_leading_guard_correct(block);
        assert_trailing_guard_correct(block);

        if (context != 0)
        {
            context->memory.allocation_stats.outstanding_allocations--;
        }
        
        free(block);
    }
}

void amqp_reset_malloc_allocation_stats()
{
    not_implemented(amqp_reset_malloc_allocation_stats);
}

