/*
   Copyright 2011 StormMQ Limited

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

#include <assert.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include "Memory/Memory.h"
#include "Context/ErrorHandling.h"

volatile int amqp_memory_trace_enabled = 1;

amqp_allocation_stats_t amqp_malloc_stats = { 0, 0 };

#define SIZE_T_BYTES (sizeof(size_t))
static const size_t mask = (size_t) 0x996e796d586067caULL;      // generated by random.org

static inline size_t byte_count_rounded_to_size_t_array_size(size_t n)
{
    return (n - 1) / SIZE_T_BYTES + 1;
}
static inline size_t calculate_bytes_to_allocate(size_t count)
{
    return (count + 3) * SIZE_T_BYTES;
}
static inline void save_guard_mask(size_t *block, size_t count)
{
    block[0] = mask ^ count;
    block[1] = count;
    block[count + 2] = mask;
}

void *amqp_malloc(size_t n TRACE_PARAMS)
{
    size_t count = byte_count_rounded_to_size_t_array_size(n);
    size_t *block = (size_t *) malloc(calculate_bytes_to_allocate(count));

#ifdef TRACE_ALLOCATIONS
    if (amqp_memory_trace_enabled)
    {
        printf("%s:%d: trace - amqp_malloc(%lu) called, block=%p, count=%lu\n", fileName, lineNumber, (unsigned long) n, (void *) block, (unsigned long) count);
    }
#endif

    amqp_malloc_stats.outstanding_allocations++;
    amqp_malloc_stats.total_allocation_calls++;

    save_guard_mask(block, count);

// TODO - ensure alignment of block[2] is OK for long double
    memset(&block[2], '\0', count * SIZE_T_BYTES);

    return (void *) &block[2];
}

static inline size_t *calculate_block_start(void *p)
{
    return ((size_t *) p) - 2;
}
static inline size_t calculate_old_count(size_t *block)
{
    return block[0] ^ mask;
}
static void assert_guard_mask_correct(size_t *block, size_t count)
{
    if (block[1] != count)
    {
        printf("Start of block corrupt! Block: %p, count: %lu, block[0]: %lx, block[1]: %lu\n",
            (void *) block, (unsigned long) count, (unsigned long) block[0], (unsigned long) block[1]);
        abort();
    }

    if (block[count + 2] != mask)
    {
        printf("End of block corrupt! Block: %p, count: %lu, block[0]: %lx, block[1]: %lu, block[count + 2]: %lx\n",
            (void *) block, (unsigned long) count, (unsigned long) block[0], (unsigned long) block[1], (unsigned long) block[count + 2]);
        abort();
    }
}

void *amqp_realloc(void *p, size_t n TRACE_PARAMS)
{
    size_t old_count, count, *old_block, *block;

    old_block = calculate_block_start(p);
    old_count = calculate_old_count(old_block);

    assert_guard_mask_correct(old_block, old_count);

    count = byte_count_rounded_to_size_t_array_size(n);
    if (count <= old_count)
    {
        return p;
    }

    block = (size_t *) realloc(old_block, calculate_bytes_to_allocate(count));

    memset(&block[old_count + 2], '\0', (count - old_count) * SIZE_T_BYTES);

#ifdef TRACE_ALLOCATIONS
    if (amqp_memory_trace_enabled)
    {
        printf("%s:%d: trace - amqp_realloc(%p, %lu) called, old_block=%p, old_count=%lu, block=%p, count=%lu\n",
            fileName, lineNumber, p, (unsigned long) n, (void *) old_block, (unsigned long) old_count, (void *) block, (unsigned long) count);
    }
#endif

    amqp_malloc_stats.total_allocation_calls++;
    save_guard_mask(block, count);

    return (void *) &block[2];
}

void amqp_free(void *p TRACE_PARAMS)
{
    size_t old_count, *block;

    if (p)
    {
        amqp_malloc_stats.outstanding_allocations--;

        block = calculate_block_start(p);
        old_count = calculate_old_count(block);

#       ifdef TRACE_ALLOCATIONS
        if (amqp_memory_trace_enabled)
        {
            printf("%s:%d: trace - amqp_free(%p) called, block=%p, count=%lu\n", fileName, lineNumber, p, (void *) block, (unsigned long) old_count);
        }
#       endif

        assert_guard_mask_correct(block, old_count);

        free(block);
    }
}

void amqp_reset_malloc_allocation_stats()
{
    amqp_malloc_stats.outstanding_allocations = 0;
    amqp_malloc_stats.total_allocation_calls = 0;
}

int amqp_assert_that_calls_to_free_match_calls_to_malloc()
{
    return amqp_malloc_stats.outstanding_allocations == 0UL;
}
