/*
   Copyright 2011 StormMQ Limited

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */
 
/*
  WARNING: This file was generated by scripts/generate. DO NOT HAND EDIT.
     scripts/generate uses:
  	scripts/generate-amqp-types.rb to generate AMQP typedefs
  	scripts/generate-decode-methods.rb to generate composite type decode methods
 */
#ifndef LIBAMQP_TRANSPORT_DECODE_SECURITY_H
#define LIBAMQP_TRANSPORT_DECODE_SECURITY_H
#ifdef __cplusplus
extern "C" {
#endif
    
/*
    <type name='sasl-mechanisms' provides='sasl-frame' class='composite' source='list'>
      <descriptor name='amqp:sasl-mechanisms:list' code='0x00000000:0x00000040'/>
      <field name='sasl-server-mechanisms' mandatory='true' type='symbol' multiple='true'/>
    </type>
*/ 
static void cleanup_sasl_mechanisms_frame(amqp_context_t *context, amqp_frame_t *frame)
{
    amqp_multiple_symbol_cleanup(context, &frame->frames.sasl.mechanisms.sasl_server_mechanisms);
}
static int decode_sasl_mechanisms_frame(amqp_context_t *context, amqp_buffer_t *buffer, amqp_frame_t *frame, amqp_type_t *field_list)
{
    const int total_fields = 1;
    int field_number = 0;
    int rc;
    
    frame->dispatch = amqp_dispatch_sasl_mechanisms;
    frame->cleanup = cleanup_sasl_mechanisms_frame;

    rc = decode_mandatory_multiple_symbol(context, field(field_list, field_number), field_number, total_fields, &frame->frames.sasl.mechanisms.sasl_server_mechanisms); field_number++;

    assert(field_number = total_fields);
    if (rc == 0)
    {
        amqp_decode_frame_error(context, "SASL Mechanisms");
    }

    return rc;  
}   

/*
    <type name='sasl-init' provides='sasl-frame' class='composite' source='list'>
      <descriptor name='amqp:sasl-init:list' code='0x00000000:0x00000041'/>
      <field name='mechanism' mandatory='true' type='symbol'/>
      <field name='initial-response' type='binary'/>
      <field name='hostname' type='string'/>
    </type>
*/ 
static void cleanup_sasl_init_frame(amqp_context_t *context, amqp_frame_t *frame)
{
    amqp_symbol_cleanup(context, &frame->frames.sasl.init.mechanism);
    amqp_binary_cleanup(context, &frame->frames.sasl.init.initial_response);
    amqp_string_cleanup(context, &frame->frames.sasl.init.hostname);
}
static int decode_sasl_init_frame(amqp_context_t *context, amqp_buffer_t *buffer, amqp_frame_t *frame, amqp_type_t *field_list)
{
    const int total_fields = 3;
    int field_number = 0;
    int rc;
    
    frame->dispatch = amqp_dispatch_sasl_init;
    frame->cleanup = cleanup_sasl_init_frame;

    rc = decode_mandatory_symbol(context, field(field_list, field_number), field_number, total_fields, &frame->frames.sasl.init.mechanism); field_number++;
    rc = rc && decode_binary(context, field(field_list, field_number), field_number, total_fields, &frame->frames.sasl.init.initial_response); field_number++;
    rc = rc && decode_string(context, field(field_list, field_number), field_number, total_fields, &frame->frames.sasl.init.hostname); field_number++;

    assert(field_number = total_fields);
    if (rc == 0)
    {
        amqp_decode_frame_error(context, "SASL Init");
    }

    return rc;  
}   

/*
    <type name='sasl-challenge' provides='sasl-frame' class='composite' source='list'>
      <descriptor name='amqp:sasl-challenge:list' code='0x00000000:0x00000042'/>
      <field name='challenge' mandatory='true' type='binary'/>
    </type>
*/ 
static void cleanup_sasl_challenge_frame(amqp_context_t *context, amqp_frame_t *frame)
{
    amqp_binary_cleanup(context, &frame->frames.sasl.challenge.challenge);
}
static int decode_sasl_challenge_frame(amqp_context_t *context, amqp_buffer_t *buffer, amqp_frame_t *frame, amqp_type_t *field_list)
{
    const int total_fields = 1;
    int field_number = 0;
    int rc;
    
    frame->dispatch = amqp_dispatch_sasl_challenge;
    frame->cleanup = cleanup_sasl_challenge_frame;

    rc = decode_mandatory_binary(context, field(field_list, field_number), field_number, total_fields, &frame->frames.sasl.challenge.challenge); field_number++;

    assert(field_number = total_fields);
    if (rc == 0)
    {
        amqp_decode_frame_error(context, "SASL Challenge");
    }

    return rc;  
}   

/*
    <type name='sasl-response' provides='sasl-frame' class='composite' source='list'>
      <descriptor name='amqp:sasl-response:list' code='0x00000000:0x00000043'/>
      <field name='response' mandatory='true' type='binary'/>
    </type>
*/ 
static void cleanup_sasl_response_frame(amqp_context_t *context, amqp_frame_t *frame)
{
    amqp_binary_cleanup(context, &frame->frames.sasl.response.response);
}
static int decode_sasl_response_frame(amqp_context_t *context, amqp_buffer_t *buffer, amqp_frame_t *frame, amqp_type_t *field_list)
{
    const int total_fields = 1;
    int field_number = 0;
    int rc;
    
    frame->dispatch = amqp_dispatch_sasl_response;
    frame->cleanup = cleanup_sasl_response_frame;

    rc = decode_mandatory_binary(context, field(field_list, field_number), field_number, total_fields, &frame->frames.sasl.response.response); field_number++;

    assert(field_number = total_fields);
    if (rc == 0)
    {
        amqp_decode_frame_error(context, "SASL Response");
    }

    return rc;  
}   

/*
    <type name='sasl-outcome' provides='sasl-frame' class='composite' source='list'>
      <descriptor name='amqp:sasl-outcome:list' code='0x00000000:0x00000044'/>
      <field name='code' mandatory='true' type='sasl-code'/>
      <field name='additional-data' type='binary'/>
    </type>
*/ 
static void cleanup_sasl_outcome_frame(amqp_context_t *context, amqp_frame_t *frame)
{
    // code
    amqp_binary_cleanup(context, &frame->frames.sasl.outcome.additional_data);
}
static int decode_sasl_outcome_frame(amqp_context_t *context, amqp_buffer_t *buffer, amqp_frame_t *frame, amqp_type_t *field_list)
{
    const int total_fields = 2;
    int field_number = 0;
    int rc;
    
    frame->dispatch = amqp_dispatch_sasl_outcome;
    frame->cleanup = cleanup_sasl_outcome_frame;

    rc = decode_mandatory_sasl_code(context, field(field_list, field_number), field_number, total_fields, &frame->frames.sasl.outcome.code); field_number++;
    rc = rc && decode_binary(context, field(field_list, field_number), field_number, total_fields, &frame->frames.sasl.outcome.additional_data); field_number++;

    assert(field_number = total_fields);
    if (rc == 0)
    {
        amqp_decode_frame_error(context, "SASL Outcome");
    }

    return rc;  
}   

#ifdef __cplusplus
}
#endif
#endif
