/*
   Copyright 2011 StormMQ Limited

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
 */

#include <assert.h>
#include <limits.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#include "Memory/Memory.h"
#include "ErrorHandling/ErrorHandling.h"

volatile int amqp_memory_trace_enabled = 0;

amqp_allocation_stats_t amqp_malloc_stats = { 0, 0 };

#define SIZE_T_BYTES (sizeof(size_t))
static const size_t mask = (size_t) 0x996e796d586067caULL;      // generated by random.org

void *amqp_malloc(size_t n TRACE_PARAMS)
{
    size_t count, *block;

#ifdef TRACE_ALLOCATIONS
    if (amqp_memory_trace_enabled)
    {
        printf("%s(%d) - amqp_malloc(%lu) called\n", fileName, lineNumber, (unsigned long) n);
    }
#endif

    amqp_malloc_stats.outstanding_allocations++;
    amqp_malloc_stats.total_allocation_calls++;

    count = (n - 1) / SIZE_T_BYTES + 1;
    block = (size_t *) malloc((count + 2) * SIZE_T_BYTES);

    block[0] = mask ^ count;
    block[count + 1] = mask;
    return memset(&block[1], '\0', count * SIZE_T_BYTES);
}

void *amqp_realloc(void *p, size_t n TRACE_PARAMS)
{
    size_t old_count, count, *block;

#ifdef TRACE_ALLOCATIONS
    if (amqp_memory_trace_enabled)
    {
        printf("%s(%d) - amqp_realloc(%p, %lu) called\n", fileName, lineNumber, p, (unsigned long) n);
    }
#endif

    amqp_malloc_stats.total_allocation_calls++;

    block = ((size_t *) p) - 1;
    old_count = block[0] ^ mask;
    assert(block[old_count + 1] == mask);

    count = (n - 1) / SIZE_T_BYTES + 1;
    block = (size_t *) realloc(block, (count + 2) * SIZE_T_BYTES);
    memset(&block[old_count], '\0', (count - old_count) * SIZE_T_BYTES);
    
    block[0] = mask ^ count;
    block[count + 1] = mask;
    return (void *) &block[1];
}

void amqp_free(void *p TRACE_PARAMS)
{
    size_t old_count, *block;

    if (p)
    {
#       ifdef TRACE_ALLOCATIONS
        if (amqp_memory_trace_enabled)
        {
            printf("%s(%d) - amqp_free(%p) called\n", fileName, lineNumber, p);
        }
#       endif

        amqp_malloc_stats.outstanding_allocations--;

        block = ((size_t *) p) - 1;
        old_count = block[0] ^ mask;
        assert(block[old_count + 1] == mask);

        free(block);
    }
}

void amqp_reset_malloc_allocation_stats()
{
    amqp_malloc_stats.outstanding_allocations = 0;
    amqp_malloc_stats.total_allocation_calls = 0;
}
