#!/bin/bash

readonly base=$(dirname "$0")
readonly source_dir="${base}/../Documentation/amqp-xml"
readonly base_dir="${base}/../src/LibAmqp"

function generate_files
{
    local cmd="${base}/$1.rb"
    if [ ! -f "$cmd" -o ! -x "$cmd" ]
    then
	echo "Cannot locate or execure $cmd"
	exit 1
    fi

    local xml_file="$2"
    local dest_dir="$3"
    local c_file="$4"
    local source="${source_dir}/${xml_file}"
    if [ ! -r "${source}" ]
    then
	echo "Cannot access XML file: ${source}"
	exit 1
    fi
    echo "${cmd} ${xml_file}"
    "$cmd" ${mode} "${source}" > "${dest_dir}/${c_file}"
}

function generate_types
{
    generate_files generate-amqp-types "$1" "${base_dir}/Amqp" "$2"
}

function generate_decode
{
    local dest_dir="${base_dir}/Transport/Decode"
    generate_files generate-decode-methods "$1" "${dest_dir}" "$2.gen"
}

generate_types transport.bare.xml AmqpTransport.h
generate_types messaging.bare.xml AmqpMessaging.h
generate_types security.bare.xml AmqpSecurity.h
generate_types transactions.bare.xml AmqpTransactions.h

generate_decode security.bare.xml decode_sasl_frame
generate_decode transport.bare.xml decode_transport_frame
