#!/bin/bash

readonly base=$(dirname "$0")
readonly cmd="${base}/generate-amqp-types.rb"

if [ ! -f "$cmd" -o ! -x "$cmd" ]
then
    echo "Cannot locate or execure $cmd"
    exit 1
fi

readonly source_dir="${base}/../Documentation/amqp-xml"
readonly dest_dir="${base}/../src/LibAmqp/Amqp"

function generate_file
{
	local xml_file="$1"
	local c_file="$2"
	local source="${source_dir}/${xml_file}"
	if [ ! -r "${source}" ]
	then
		echo "Cannot access XML file: ${source}"
		exit 1
	fi
	echo "${xml_file}"
	"$cmd" "${source}" > "${dest_dir}/${c_file}"
}

generate_file transport.bare.xml AmqpTransport.h
generate_file security.bare.xml AmqpSecurity.h
